"""Create all database tables

Revision ID: 5dd6313832d5
Revises: 7bd5d3f1e456
Create Date: 2025-11-06 09:43:29.119835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5dd6313832d5'
down_revision = '7bd5d3f1e456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('document_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('institution', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('ocr_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'verified_by')
    op.drop_column('documents', 'access_level')
    op.drop_column('documents', 'searchable_text')
    op.drop_column('documents', 'file_name')
    op.drop_column('documents', 'original_file_name')
    op.drop_column('documents', 'extracted_data')
    op.drop_column('documents', 'document_number')
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'file_size_bytes')
    op.drop_column('documents', 'share_expires')
    op.drop_column('documents', 'verified_at')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'last_viewed_at')
    op.drop_column('documents', 'date_issued')
    op.drop_column('documents', 'view_count')
    op.drop_column('documents', 'ocr_processed_at')
    op.drop_column('documents', 'is_verified')
    op.drop_column('documents', 'share_token')
    op.drop_column('documents', 'ocr_status')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'subcategory')
    op.drop_column('documents', 'is_shared')
    op.add_column('medical_visits', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_medical_visits_user_id'), 'medical_visits', ['user_id'], unique=False)
    op.create_foreign_key(None, 'medical_visits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_visits', type_='foreignkey')
    op.drop_index(op.f('ix_medical_visits_user_id'), table_name='medical_visits')
    op.drop_column('medical_visits', 'user_id')
    op.add_column('documents', sa.Column('is_shared', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('ocr_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('share_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('ocr_processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('date_issued', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('last_viewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('share_expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('document_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('original_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('searchable_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('access_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('verified_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'notes')
    op.drop_column('documents', 'extraction_metadata')
    op.drop_column('documents', 'ocr_text')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'institution')
    op.drop_column('documents', 'document_date')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'filename')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###